### ISSUE TITLE
Meteor giving warning for using Template.myTemplate.topGenresChart instead of helpers

### ISSUE THREAD

**Issue by kidsil** [MaazAli/Meteor-HighCharts#17]
Hi,
I'm getting a warning from Meteor for defining a function directly in the template object instead of a helper.

```(blaze.js:71) Warning: Assigning helper with `Template.myTemplate.stockChart = ...` is deprecated.  Use `Template.myTemplate.helpers(...)` instead.```

I wonder if it would be easier to make highchartsHelper inheritable? That way one could add parameters to the stockChart object as well..

**Comment by MaazAli** [comment]
@kidsil, I should update the readme but you should be defining your helpers in an object.
Like so: 
```
Template.myTemplate.helpers({
   stockChart: function() {

  }
});
```

It shouldn't change any of the functionality. We can't make the helper inheritable because meteor doesn't allow for that as far as I know. Additionally, it's the interface to the addon so it makes sense to be stand alone.

**Comment by kidsil** [comment]
@MaazAli  hey thanks for the help, I'm wondering though, if I want to give make the series dynamic, should I just define it as ```series: Session.get(...)``` (for example) ?
Is there a better approach for that?

**Comment by MaazAli** [comment]
@kidsil you'll just need to update your chart object with the updated data, no need to touch the helper.

Take a look at this issue which has a solution: https://github.com/MaazAli/Meteor-HighCharts/issues/9

**Comment by kidsil** [comment]
@MaazAli Thanks! That helped a lot! :)
